language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# command to install dependencies
# cache:
#   - "pip"
install:
  - "pip install -r requirements.txt"
  - "pip install pep8"
# command to run tests
script:
  - python setup.py test
  - pep8 .
